blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/OhMyDitzzy/scalara/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://github.com/OhMyDitzzy/scalara/wiki
    about: Check out the project documentation